# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosExample
  
  pod 'MessageKit'
  pod 'MessageInputBar'
  
  target 'iosExampleTests1' do
    inherit! :search_paths
    # Pods for testing
  end

end
